spring:
  application:
    name: learn-graphql-java
  main:
    allow-bean-definition-overriding: true

graphql:
  servlet:
    max-query-depth: 5
    exception-handlers-enabled: true #default is false. So if not enabled, than GQLS will over write specific exception with more general exception and message
  playground:
    mapping: /playground
    endpoint: /graphql
    enabled: true #you may turn it off in prod
    pageTitle: Playground
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Get Bank Account
        query: classpath:playground/get_bank_account.graphql
        variables: classpath:playground/bank_account_variables.json

logging:
  pattern:
    console: -%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%X{correlation_id}){red} %m%n%wEx

voyager:
  enabled: true #you may turn it off in prod
